# Generated by Django 2.0.1 on 2018-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '问题选择', 'verbose_name_plural': '问题选择'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '提问', 'verbose_name_plural': '提问'},
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
